# Generated by Django 5.2.1 on 2025-05-21 11:26

import autoslug.fields
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_large',
            field=models.ImageField(upload_to='products/images/large/', verbose_name='Изображение большого размера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(upload_to='products/images/medium/', verbose_name='Изображение среднего размера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(default=None, upload_to='products/images/small/', verbose_name='Изображение малого размера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=shop.models.transliterate_name, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=shop.models.transliterate_name, unique=True, verbose_name='Slug'),
        ),
    ]
